spring:
  application:
    name: Fundacred Challenge - DEV
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:./database/data/challengedb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

challenge:
  secret: Fundacred Secret